version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: jhipster
      POSTGRES_PASSWORD: jhipster
      POSTGRES_DB: portfolio_db
    ports:
      - '5432:5432'
