package com.example.portfolio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PortfolioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortfolioAllPropertiesEquals(Portfolio expected, Portfolio actual) {
        assertPortfolioAutoGeneratedPropertiesEquals(expected, actual);
        assertPortfolioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortfolioAllUpdatablePropertiesEquals(Portfolio expected, Portfolio actual) {
        assertPortfolioUpdatableFieldsEquals(expected, actual);
        assertPortfolioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortfolioAutoGeneratedPropertiesEquals(Portfolio expected, Portfolio actual) {
        assertThat(actual)
            .as("Verify Portfolio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortfolioUpdatableFieldsEquals(Portfolio expected, Portfolio actual) {
        assertThat(actual)
            .as("Verify Portfolio relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortfolioUpdatableRelationshipsEquals(Portfolio expected, Portfolio actual) {
        assertThat(actual)
            .as("Verify Portfolio relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
